## Learning Jupyter Notebook

In [1]:
40 + 2 

42

In [2]:
import numpy as np 

In [4]:
Out[1]

42

In [5]:
 x = Out[1]

In [6]:
x

42

In [9]:
np.sin(90)

0.8939966636005579

In [13]:
np.sin?

In [15]:
#Help window and source code of the function 
np.any??

In [16]:
#current working directory 
%pwd

'/Users/hilaryalabi/DATA SCIENCE FOUNDATIONS: PYTHON SCIENTIFIC STACK '

In [18]:
#Time it takes to run 

%%time
for i in range (5): 
    print(np.sin(5))

-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
CPU times: user 557 µs, sys: 479 µs, total: 1.04 ms
Wall time: 3.4 ms


In [20]:
# Magic functions 
%magic

In [19]:
# Calling the shell folders 
!ls /var/log

Bluetooth                 dm                        system.log
CoreDuet                  emond                     system.log.0.gz
DiagnosticMessages        fsck_apfs.log             system.log.1.gz
apache2                   fsck_apfs_error.log       system.log.2.gz
asl                       fsck_hfs.log              system.log.3.gz
com.apple.wifivelocity    install.log               uucp
com.apple.xpc.launchd     install.log.0.gz          wifi.log
cups                      mDNSResponder             wifi.log.0.bz2
daily.out                 powermanagement           wifi.log.1.bz2
displaypolicy             ppp                       wifi.log.2.bz2
displaypolicyd.stdout.log shutdown_monitor.log      wifi.log.3.bz2


## NumPy 

In [21]:
import numpy as np 

In [22]:
# Numpy Array - looks like a python list 
arr = np.array([1,2,3])
arr 

array([1, 2, 3])

In [23]:
len(arr)

3

In [26]:
arr[1]

2

In [27]:
type(arr[1])

numpy.int64

In [29]:
arr.dtype

dtype('int64')

In [32]:
arr32 = np.array([1,2,3], dtype=np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [33]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)


In [37]:
# How much time it took to multiply the 1 millin floating point numbers 
%time v1 * v2

CPU times: user 4.48 ms, sys: 5.69 ms, total: 10.2 ms
Wall time: 8.52 ms


array([0.48045867, 0.09706366, 0.49508114, ..., 0.09236235, 0.2678351 ,
       0.43614506])

Times will change but, np array are different from classic algebra and matrixs - to get a dot product we use a dot 

In [38]:
np.dot(arr, arr)

14

In [39]:
# to get the dot product 
arr @ arr 

14

In [40]:
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
v.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
mat = np.arange(12). reshape((4,3))
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
mat.shape

(4, 3)

In [46]:
# change a value in the matrix 
#mat2[1,2] = 17 

In [49]:
# Slicing the Data 
mat[0]


array([0, 1, 2])

In [50]:
mat[1, 1]

4

In [53]:
mat[:,0] # Gives all the columns in the first row 

array([0, 3, 6, 9])

In [54]:
mat[0, :] # Gives all the rows 

array([0, 1, 2])

In [56]:
mat[1:, 2:]

array([[ 5],
       [ 8],
       [11]])

In [58]:
mat[1:, 2:] = 7 
mat

array([[ 0,  1,  2],
       [ 3,  4,  7],
       [ 6,  7,  7],
       [ 9, 10,  7]])

In [59]:
# Boolean Indexing 

In [60]:
mat = arr

In [62]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [63]:
arr >= 1

array([False,  True,  True])

In [65]:
arr[arr>=1]

array([1, 2])

In [66]:
arr = np.arange(10)

In [68]:
arr[(arr>2)&(arr<6)]

array([3, 4, 5])

In [69]:
arr[(arr>7)|(arr<2)]

array([0, 1, 8, 9])

In [70]:
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [76]:
mat = np.random.rand(5,5)
mat

array([[0.90316262, 0.63480462, 0.81359753, 0.52907371, 0.26235562],
       [0.9758725 , 0.67233653, 0.28316112, 0.77579455, 0.79721357],
       [0.51586587, 0.14013241, 0.46835901, 0.41743445, 0.67554339],
       [0.89079493, 0.45086415, 0.86739009, 0.52072624, 0.78472295],
       [0.60205673, 0.2874304 , 0.9129047 , 0.27593146, 0.67343321]])

In [77]:
# al the values that are more than one standard devaition from the mean 

mat[np.abs(mat - mat.mean()) > 1.5*mat.std()]

array([0.9758725 , 0.14013241])

In [79]:
np.abs(mat - mat.mean()) > 1.5*mat.std()

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
# How many odd numbers in the array ? 



## Pandas 

In [80]:
from os import path 
fname = path.expanduser('~/Desktop/Ex_Files_Data_Science_Python/Exercise Files/Ch04/04_02/track.csv')


In [90]:
import pandas as pd 
df = pd.read_csv(fname)

In [82]:
len(df)

740

In [83]:
df.columns

Index(['time', 'lat', 'lng', 'height'], dtype='object')

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 4 columns):
time      740 non-null object
lat       740 non-null float64
lng       740 non-null float64
height    740 non-null float64
dtypes: float64(3), object(1)
memory usage: 23.2+ KB


In [88]:
df.head()

time        lat        lng      height
0  2015-08-20 03:48:07.235  35.015021  32.519585  136.199997
1  2015-08-20 03:48:24.734  35.014954  32.519606  126.599998
2  2015-08-20 03:48:25.660  35.014871  32.519612  123.000000
3  2015-08-20 03:48:26.819  35.014824  32.519654  120.500000
4  2015-08-20 03:48:27.828  35.014776  32.519689  118.900002

In [86]:
df.dtypes

time       object
lat       float64
lng       float64
height    float64
dtype: object

In [93]:
df = pd.read_csv(fname, parse_dates=['time'])

In [94]:
df.head()

time        lat        lng      height
0 2015-08-20 03:48:07.235  35.015021  32.519585  136.199997
1 2015-08-20 03:48:24.734  35.014954  32.519606  126.599998
2 2015-08-20 03:48:25.660  35.014871  32.519612  123.000000
3 2015-08-20 03:48:26.819  35.014824  32.519654  120.500000
4 2015-08-20 03:48:27.828  35.014776  32.519689  118.900002

In [95]:
df.dtypes

time      datetime64[ns]
lat              float64
lng              float64
height           float64
dtype: object

Now the data is in the right format - so time in in datetime ofrmat instead of object 

In [97]:
df['lat']

0      35.015021
1      35.014954
2      35.014871
3      35.014824
4      35.014776
         ...    
735    35.014387
736    35.014355
737    35.014279
738    35.014264
739    35.014212
Name: lat, Length: 740, dtype: float64

In [99]:
df.lat #Dot NOTATION NOT FAVOURABLE BEVAUSE WHEN SPACES COME YOU CAN'T USE DOTS

0      35.015021
1      35.014954
2      35.014871
3      35.014824
4      35.014776
         ...    
735    35.014387
736    35.014355
737    35.014279
738    35.014264
739    35.014212
Name: lat, Length: 740, dtype: float64

In [100]:
# Printing rows 
df['lat'][0]

35.015021000000004

In [101]:
# Printing rows 
df.loc[0]

time      2015-08-20 03:48:07.235000
lat                           35.015
lng                          32.5196
height                         136.2
Name: 0, dtype: object

In [103]:
#df.loc also works with slices 
df.loc[2:7]

time        lat        lng      height
2 2015-08-20 03:48:25.660  35.014871  32.519612  123.000000
3 2015-08-20 03:48:26.819  35.014824  32.519654  120.500000
4 2015-08-20 03:48:27.828  35.014776  32.519689  118.900002
5 2015-08-20 03:48:29.720  35.014704  32.519691  119.900002
6 2015-08-20 03:48:30.669  35.014657  32.519734  120.900002
7 2015-08-20 03:48:33.793  35.014563  32.519719  121.699997

In [104]:
df[['lat' , 'lng']][2:7]

lat        lng
2  35.014871  32.519612
3  35.014824  32.519654
4  35.014776  32.519689
5  35.014704  32.519691
6  35.014657  32.519734

In [105]:
df.index

RangeIndex(start=0, stop=740, step=1)